#!/bin/bash

unset "$(git rev-parse --local-env-vars)"; git -C /home/gha/status-bare/.git describe --always

# Pull the production main branch for the website repo
cd /home/gha/status || exit
git --git-dir=/home/gha/status/.git pull origin dev
git --git-dir=/home/gha/status/.git push dev dev
